# Generated by Django 5.2 on 2025-04-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('local_address', models.TextField(max_length=512)),
                ('permanent_address', models.TextField(max_length=512)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=64)),
                ('gst', models.CharField(blank=True, max_length=15, verbose_name='GST Number')),
                ('location', models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=13)),
                ('type', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='first', max_length=6)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
