# Generated by Django 5.2 on 2025-04-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='local_address',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='client',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
